export { apiRequest, API_BASE } from "./client";
export { dashboardApi } from "./dashboard/dashboard";
export { customerSalesApi } from "./customers/customerSales";
export { addCustomerApi } from "./customers/addCustomer";
export { customersExportApi } from "./customers/export";
export { salesApi } from "./sales/sales";
export { paymentSlabsApi } from "./sales/paymentSlabs";
export { receivedPaymentsApi } from "./sales/receivedPayments";
export { salesExportApi } from "./sales/export";
export { inventoryApi } from "./inventory/inventory";
export { shareholderApi } from "./shareholder/shareholder";
export { projectsApi } from "./projects/projects";
export { settingsApi } from "./settings/settings";
