import type {
  Contractor,
  Material,
  OverdueBill,
  PurchaseOrder,
  PurchaseRequest,
  Supplier,
  WorkOrder,
  WorkOrderRequest,
} from "./inventoryTypes";

export const MOCK_MATERIALS: Material[] = [
  {
    id: "MAT-001",
    name: "OPC Cement 53 Grade",
    type: "Cement",
    workCategories: ["Civil", "Structural"],
    unit: "bags",
    quantity: 42,
    reorderLevel: 100,
    unitCost: 385,
    currentSupplierId: "SUP-0001",
    currentSupplierName: "Shree Cement Traders",
  },
  {
    id: "MAT-002",
    name: "TMT Steel 12mm",
    type: "Steel",
    workCategories: ["Structural", "Civil"],
    unit: "tons",
    quantity: 8,
    reorderLevel: 15,
    unitCost: 62000,
    currentSupplierId: "SUP-0002",
    currentSupplierName: "Metro Steel Depot",
  },
  {
    id: "MAT-003",
    name: "River Sand",
    type: "Aggregate",
    workCategories: ["Civil", "Plastering"],
    unit: "cu.ft.",
    quantity: 220,
    reorderLevel: 150,
    unitCost: 55,
    currentSupplierId: "SUP-0003",
    currentSupplierName: "Green Build Materials",
  },
  {
    id: "MAT-004",
    name: "AAC Blocks",
    type: "Masonry",
    workCategories: ["Civil", "Masonry"],
    unit: "nos",
    quantity: 1800,
    reorderLevel: 500,
    unitCost: 78,
    currentSupplierId: "SUP-0003",
    currentSupplierName: "Green Build Materials",
  },
  {
    id: "MAT-005",
    name: "Vitrified Tiles",
    type: "Finishing",
    workCategories: ["Finishing", "Civil"],
    unit: "sq.ft.",
    quantity: 95,
    reorderLevel: 200,
    unitCost: 62,
    currentSupplierId: "SUP-0004",
    currentSupplierName: "Sankalp Hardware & Tiles",
  },
  {
    id: "MAT-006",
    name: "Ready Mix Concrete M25",
    type: "Concrete",
    workCategories: ["Structural", "Civil"],
    unit: "cu.m.",
    quantity: 12,
    reorderLevel: 20,
    unitCost: 5200,
    currentSupplierId: "SUP-0001",
    currentSupplierName: "Shree Cement Traders",
  },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "SUP-0001",
    name: "Shree Cement Traders",
    workCategories: ["Civil", "Structural"],
    phone: "+91 98765 43210",
    email: "sales@shreecement.example",
    address: "MIDC Road, Pune",
    pinCode: "411019",
    paymentTotal: 200000,
    paymentRemaining: 125000,
    status: "active",
  },
  {
    id: "SUP-0002",
    name: "Metro Steel Depot",
    workCategories: ["Structural", "Civil"],
    phone: "+91 98220 11445",
    email: "orders@metrosteel.example",
    address: "Industrial Estate, Nashik",
    pinCode: "422007",
    paymentTotal: 400000,
    paymentRemaining: 285000,
    status: "active",
  },
  {
    id: "SUP-0003",
    name: "Green Build Materials",
    workCategories: ["Civil", "Plastering", "Masonry"],
    phone: "+91 98901 22334",
    address: "Station Road, Aurangabad",
    pinCode: "431001",
    paymentTotal: 0,
    paymentRemaining: 0,
    status: "active",
  },
  {
    id: "SUP-0004",
    name: "Sankalp Hardware & Tiles",
    workCategories: ["Finishing", "Civil"],
    phone: "+91 97654 88990",
    email: "info@sankalptiles.example",
    address: "Market Yard, Satara",
    pinCode: "415001",
    paymentTotal: 80000,
    paymentRemaining: 42000,
    status: "inactive",
  },
];

export const MOCK_CONTRACTORS: Contractor[] = [
  {
    id: "CON-0001",
    name: "Ramesh Plastering Works",
    workProfile: "Internal & external plastering",
    workCategories: ["Plastering", "Civil"],
    phone: "+91 98111 22001",
    address: "Camp, Pune",
    pinCode: "411001",
    paymentTotal: 150000,
    paymentRemaining: 45000,
    status: "active",
    trade: "Plastering",
  },
  {
    id: "CON-0002",
    name: "Apex Electrical Services",
    workProfile: "Electrical rough-in and fit-outs",
    workCategories: ["Electrical"],
    phone: "+91 98222 33002",
    paymentTotal: 90000,
    paymentRemaining: 90000,
    status: "active",
    trade: "Electrical",
  },
  {
    id: "CON-0003",
    name: "Nirmiti Civil Contractors",
    workProfile: "RCC and civil works",
    workCategories: ["Civil", "Structural"],
    phone: "+91 98333 44003",
    paymentTotal: 500000,
    paymentRemaining: 120000,
    status: "inactive",
    trade: "Civil",
  },
];

export const MOCK_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: "REQ-000001",
    requestNo: "REQ-000001",
    supplierId: "SUP-0001",
    supplierName: "Shree Cement Traders",
    materialId: "MAT-001",
    materialName: "OPC Cement 53 Grade",
    productDescription: "53 grade OPC for RCC columns — Wing A",
    unit: "bags",
    quantity: 200,
    unitPrice: 380,
    lineTotal: 76000,
    gstRate: 18,
    gstAmount: 13680,
    roundOff: 0,
    grandTotal: 89680,
    shipToAddress: "Site store, Nirmiti Heights, Pune",
    orderDate: "2026-07-15",
    status: "pending",
  },
  {
    id: "REQ-000002",
    requestNo: "REQ-000002",
    supplierId: "SUP-0002",
    supplierName: "Metro Steel Depot",
    materialId: "MAT-002",
    materialName: "TMT Steel 12mm",
    productDescription: "FE 500 TMT bars for slab — Tower B",
    unit: "tons",
    quantity: 5,
    unitPrice: 55000,
    lineTotal: 275000,
    gstRate: 18,
    gstAmount: 49500,
    roundOff: 0,
    grandTotal: 324500,
    shipToAddress: "Site store, Nirmiti Heights, Pune",
    orderDate: "2026-07-16",
    status: "pending",
  },
];

export const MOCK_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "PO-000001",
    supplierId: "SUP-0001",
    supplierName: "Shree Cement Traders",
    materialId: "MAT-001",
    materialName: "OPC Cement 53 Grade",
    productDescription: "Bulk cement order — foundation",
    unit: "bags",
    quantity: 500,
    unitPrice: 340,
    subTotal: 169491.53,
    gstRate: 18,
    gstAmount: 30508.47,
    roundOff: 0,
    grandTotal: 200000,
    orderDate: "2026-07-10",
    status: "received",
    amountTotal: 200000,
    amountPaid: 75000,
    shipToAddress: "Site store, Nirmiti Heights, Pune",
    payable: true,
  },
  {
    id: "PO-000002",
    supplierId: "SUP-0002",
    supplierName: "Metro Steel Depot",
    materialId: "MAT-002",
    materialName: "TMT Steel 12mm",
    productDescription: "TMT for columns and beams",
    unit: "tons",
    quantity: 12,
    unitPrice: 28248.59,
    subTotal: 338983.05,
    gstRate: 18,
    gstAmount: 61016.95,
    roundOff: 0,
    grandTotal: 400000,
    orderDate: "2026-07-12",
    status: "partial",
    amountTotal: 400000,
    amountPaid: 115000,
    shipToAddress: "Site store, Nirmiti Heights, Pune",
    payable: true,
  },
  {
    id: "PO-000003",
    supplierId: "SUP-0003",
    supplierName: "Green Build Materials",
    materialId: "MAT-003",
    materialName: "River Sand",
    productDescription: "Washed river sand for plaster",
    unit: "cu.ft.",
    quantity: 800,
    unitPrice: 52.97,
    subTotal: 42372.88,
    gstRate: 18,
    gstAmount: 7627.12,
    roundOff: 0,
    grandTotal: 50000,
    orderDate: "2026-07-13",
    status: "pending",
    amountTotal: 50000,
    amountPaid: 0,
    shipToAddress: "Site store, Nirmiti Heights, Pune",
    payable: true,
  },
  {
    id: "PO-000004",
    supplierId: "SUP-0004",
    supplierName: "Sankalp Hardware & Tiles",
    materialId: "MAT-005",
    materialName: "Vitrified Tiles",
    productDescription: "600x600 vitrified floor tiles",
    unit: "sq.ft.",
    quantity: 1200,
    unitPrice: 56.5,
    subTotal: 67800,
    gstRate: 18,
    gstAmount: 12204,
    roundOff: 0,
    grandTotal: 80004,
    orderDate: "2026-07-14",
    status: "pending",
    amountTotal: 80004,
    amountPaid: 38000,
    shipToAddress: "Site store, Nirmiti Heights, Pune",
    payable: true,
  },
];

export const MOCK_WORK_ORDER_REQUESTS: WorkOrderRequest[] = [
  {
    id: "WOR-000001",
    requestNo: "WOR-000001",
    contractorId: "CON-0001",
    contractorName: "Ramesh Plastering Works",
    workCategories: ["Plastering", "Civil"],
    workProfile: "Internal plastering",
    description: "Wing A floors 1–3 plastering work",
    dateOfIssue: "2026-07-14",
    commitmentDate: "2026-07-28",
    materialIssues: [
      {
        materialId: "MAT-001",
        materialName: "OPC Cement 53 Grade",
        unit: "bags",
        quantity: 50,
      },
    ],
    status: "pending",
    createdAt: "2026-07-14T10:00:00.000Z",
  },
];

export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: "WO-000001",
    contractorId: "CON-0001",
    contractorName: "Ramesh Plastering Works",
    title: "Internal plastering — Wing A floors 1–3",
    description: "Internal plastering — Wing A floors 1–3",
    workProfile: "Plastering",
    workCategories: ["Plastering"],
    trade: "Plastering",
    materialIds: ["MAT-001", "MAT-003"],
    materialIssues: [
      {
        materialId: "MAT-001",
        materialName: "OPC Cement 53 Grade",
        unit: "bags",
        quantity: 40,
      },
    ],
    materialReturns: [],
    dateOfIssue: "2026-07-08",
    commitmentDate: "2026-07-20",
    startDate: "2026-07-08",
    status: "in-progress",
    amountTotal: 150000,
    amountPaid: 105000,
    payable: true,
  },
  {
    id: "WO-000002",
    contractorId: "CON-0002",
    contractorName: "Apex Electrical Services",
    title: "Electrical rough-in — common areas",
    description: "Electrical rough-in — common areas",
    workProfile: "Electrical",
    workCategories: ["Electrical"],
    trade: "Electrical",
    materialIds: [],
    dateOfIssue: "2026-07-11",
    commitmentDate: "2026-07-25",
    startDate: "2026-07-11",
    status: "open",
    amountTotal: 90000,
    amountPaid: 0,
    payable: true,
  },
  {
    id: "WO-000003",
    contractorId: "CON-0003",
    contractorName: "Nirmiti Civil Contractors",
    title: "Slab casting support — Floor 4",
    description: "Slab casting support — Floor 4",
    workProfile: "Civil",
    workCategories: ["Civil", "Structural"],
    trade: "Civil",
    materialIds: ["MAT-006", "MAT-002"],
    dateOfIssue: "2026-07-01",
    commitmentDate: "2026-07-10",
    startDate: "2026-07-01",
    status: "completed",
    amountTotal: 500000,
    amountPaid: 380000,
    payable: true,
  },
];


export const MOCK_OVERDUE_BILLS: OverdueBill[] = [
  {
    id: "BILL-501",
    partyName: "Metro Steel Depot",
    partyType: "supplier",
    billRef: "INV-MS-2026-118",
    dueAmount: 285000,
    dueDate: "2026-06-28",
  },
  {
    id: "BILL-502",
    partyName: "Ramesh Plastering Works",
    partyType: "contractor",
    billRef: "RA-PL-45",
    dueAmount: 95000,
    dueDate: "2026-07-01",
  },
  {
    id: "BILL-503",
    partyName: "Green Build Materials",
    partyType: "supplier",
    billRef: "GBM-7721",
    dueAmount: 142500,
    dueDate: "2026-07-05",
  },
];

/** Pending / total payment KPI (₹) — sum of overdue bill amounts for Phase 1 mock */
export const MOCK_PENDING_BILLS_TOTAL = MOCK_OVERDUE_BILLS.reduce(
  (sum, b) => sum + b.dueAmount,
  0
);
